#!/usr/bin/env python3

import argparse
import os
import sys

from PIL import Image

def scale_image(scale, src, dst=None):
    img = Image.open(src)
    new_size = (img.width * scale, img.height * scale)
    img_resized = img.resize(new_size, Image.Resampling.NEAREST)

    dir, filename = os.path.split(src)
    base, ext = os.path.splitext(filename)

    if dst is None:
        dst = os.path.join(dir, f"{base}_{scale}x{ext}")
    else:
        base, ext = os.path.splitext(dst)
        dst = f"{base}_{scale}x{ext}"

    img_resized.save(dst)
    print(f"Saved scaled image to {dst}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Scale a pixel image by 2x, 3x, or 4x.")

    if len(sys.argv) == 1:
        parser.print_help(sys.stderr)
        sys.exit(1)

    parser.add_argument("-s", type=int, choices=[2, 3, 4], required=True, help="Scaling factor (2, 3, or 4).")
    parser.add_argument("-i", type=str, required=True, help="Input PNG file.")
    parser.add_argument("-o", type=str, required=False, help="Output PNG file.")
    args = parser.parse_args()
    scale_image(args.s, args.i, args.o)
